apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opportunity-portal

resources:
  - namespace.yaml
  - secret-db.yaml
  - deployment-auth.yaml
  - service-auth.yaml
  - deployment-opportunity.yaml
  - service-opportunity.yaml
  - deployment-web.yaml
  - service-web.yaml
  - hpa-auth.yaml
  - hpa-opportunity.yaml
